# Generated by Django 5.2.3 on 2025-06-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finalized',
            new_name='is_finished',
        ),
    ]
