# Generated by Django 5.2.3 on 2025-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_finalized',
            new_name='is_finished',
        ),
    ]
